/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nJuuVKkThFh
 */
import Link from "next/link";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";

export function Component() {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex-1">
        <section className="w-full flex justify-center py-6 sm:py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <Image
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
                height="550"
                src="/images/sitework3.jpeg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Quality Sitework Services in Florida
                  </h1>
                  <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                    We offer top-notch sitework services, ensuring your construction projects are
                    built on solid ground.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="/contact"
                  >
                    Get a Quote
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border text-white border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Our Services
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full flex justify-center py-12 md:py-24 lg:py-32 px-6">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl py-2 font-bold tracking-tighter text-center sm:text-5xl xl:text-6xl/none">
              Our Services
            </h2>
            <div className="grid gap-6 lg:grid-cols-3">
              <Card className="overflow-hidden rounded-xl shadow-lg">
                <CardHeader className="bg-gray-100 p-4">
                  <h3 className="text-xl font-bold">Excavation</h3>
                </CardHeader>
                <CardContent className="p-4">
                  <p className="text-gray-500">
                    We provide top-notch excavation services for all types of construction projects.
                  </p>
                </CardContent>
              </Card>
              <Card className="overflow-hidden rounded-xl shadow-lg">
                <CardHeader className="bg-gray-100 p-4">
                  <h3 className="text-xl font-bold">Site Preparation</h3>
                </CardHeader>
                <CardContent className="p-4">
                  <p className="text-gray-500">
                    Our team ensures your site is prepared properly, meeting all the necessary
                    requirements.
                  </p>
                </CardContent>
              </Card>
              <Card className="overflow-hidden rounded-xl shadow-lg">
                <CardHeader className="bg-gray-100 p-4">
                  <h3 className="text-xl font-bold">Final Grading</h3>
                </CardHeader>
                <CardContent className="p-4">
                  <p className="text-gray-500">
                    We provide precise final grading services to prepare your site for landscaping
                    and construction.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full flex justify-center py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-100">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Ready to Start Your Project?
              </h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Let's build something great together. Get in touch with us today for a free quote.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row lg:justify-end">
              <Link href="/contact">
                <Button className="inline-flex h-12 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300">
                  Get a Quote
                </Button>
              </Link>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

export function HardHatIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 18a1 1 0 0 0 1 1h18a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v2z" />
      <path d="M10 10V5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v5" />
      <path d="M4 15v-3a6 6 0 0 1 6-6h0" />
      <path d="M14 6h0a6 6 0 0 1 6 6v3" />
    </svg>
  );
}
