/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WFdzbTH9Ozg
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { JSX, SVGProps } from "react";

export function ContactForm() {
  return (
    <Card className="max-w-lg mx-auto p-8 space-y-6">
      <CardHeader className="mb-6">
        <CardTitle className="text-2xl font-semibold">Contact Us</CardTitle>
        <CardDescription className="text-gray-500">
          Please fill out the form below and we will get back to you as soon as possible.
          <div className="flex py-2 gap-2">
            <MailboxIcon className="w-5 h-5" />
            <Link className="text-blue-600" href="mailto:info@g2sitework.com">
              info@g2sitework.com
            </Link>
          </div>
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input
              className="w-full focus-visible:ring-gray-700"
              id="name"
              placeholder="First and Last Name"
              required
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              className="w-full focus-visible:ring-gray-700"
              id="email"
              placeholder="name@xyz.com"
              required
              type="email"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            <Textarea
              className="w-full min-h-[100px] focus-visible:ring-gray-700"
              id="message"
              placeholder="Your Message"
              required
            />
          </div>
          <Button className="w-full bg-black text-white">Submit</Button>
        </form>
      </CardContent>
    </Card>
  );
}

function MailboxIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  );
}
